INSERT INTO `Settings` VALUES ('COURTS_CLASS1_MIN','0');
INSERT INTO `Settings` VALUES ('COURTS_CLASS2_MIN','9');
INSERT INTO `Settings` VALUES ('COURTS_MAX','9');
INSERT INTO `Settings` VALUES ('DURATIONMATCH','10');
INSERT INTO `Settings` VALUES ('DURATIONPPOSTMATCH','0.5');
INSERT INTO `Settings` VALUES ('DURATIONPREMATCH','1');
INSERT INTO `Settings` VALUES ('EDITION','16');
INSERT INTO `Settings` VALUES ('YEAR','2019');
INSERT INTO `Settings` VALUES ('TITLE','18. Goddelauer Badminton Nachtturnier');
INSERT INTO `Settings` VALUES ('LOGO','TSV');
INSERT INTO `Settings` VALUES ('MPC_HOST','192.168.2.15');
INSERT INTO `Settings` VALUES ('MPC_PLAYLIST','Mixed');
INSERT INTO `Settings` VALUES ('MPC_VOLUME_EFFECT','50');
INSERT INTO `Settings` VALUES ('MPC_VOLUME_MUSIC','30');
INSERT INTO `Settings` VALUES ('SHOW_EXECUTION_TIME','0');
INSERT INTO `Settings` VALUES ('SIMULATION_ROUNDS','10');

